version: '3.8'

networks:
  xibo-network:
    name: "${CUSTOMER_ID}_xibo_network"
    external: false
  traefik:
    external: true

volumes:
  db-data:
    name: "${CUSTOMER_ID}_db_data"
  library:
    name: "${CUSTOMER_ID}_library"
  backup:
    name: "${CUSTOMER_ID}_backup"

services:
  db:
    image: mysql:5.7
    container_name: "${CUSTOMER_ID}_xibo_db"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --innodb-file-format=Barracuda --innodb-file-per-table=1 --innodb-large-prefix=1
    networks:
      - xibo-network

  memcached:
    image: memcached:alpine
    container_name: "${CUSTOMER_ID}_xibo_memcached"
    command: memcached -m ${MEMCACHED_MEMORY:-64}
    restart: always
    networks:
      - xibo-network

  cms-web:
    image: ghcr.io/xibosignage/xibo-cms:release-4.3.0
    container_name: "${CUSTOMER_ID}_xibo_cms"
    volumes:
      - library:/var/www/cms/library
      - backup:/var/www/backup
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: ${DB_PASSWORD}
      CMS_SERVER_NAME: ${CUSTOMER_DOMAIN}
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211
      APACHE_PORT: 80  # Ensure Apache listens on port 80 internally
    depends_on:
      - db
      - memcached
    deploy:
      resources:
        limits:
          memory: ${CMS_MEMORY_LIMIT:-1g}
    networks:
      - xibo-network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CUSTOMER_ID}-xibo.rule=Host(`${CUSTOMER_DOMAIN}.localhost`)"
      - "traefik.http.routers.${CUSTOMER_ID}-xibo.entrypoints=web"
      - "traefik.http.services.${CUSTOMER_ID}-xibo.loadbalancer.server.port=80"  # Changed from 8000 to 80
      - "traefik.http.routers.${CUSTOMER_ID}-xibo.service=${CUSTOMER_ID}-xibo-service"
      - "traefik.docker.network=traefik"

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:1.0
    container_name: "${CUSTOMER_ID}_xibo_xmr"
    restart: always
    ports:
      - "9505"  # Let Docker assign random port to avoid conflicts
    networks:
      - xibo-network